# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipms', '0002_studentslotmatrix_unastaffslotmatrix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSlotMatrix',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='UnaStaffSlotMatrix',
            new_name='UNA_STAFF',
        ),
    ]
