# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipms', '0007_spotcheck_yourid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourid', models.IntegerField(default=0)),
                ('yourstatus', models.CharField(max_length=30)),
                ('yourpin', models.CharField(max_length=30)),
            ],
        ),
    ]
