# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipms', '0009_auto_20160325_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='pin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driversstaff',
            name='pin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='requesttest',
            name='pin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinstant',
            name='pin',
            field=models.CharField(max_length=30),
        ),
    ]
